services:
  app-service:
    build:
      context: ../.. # This sets the build context to two directories up
      dockerfile: apps/crypto/app/Dockerfile # Specify the path to your Dockerfile
    env_file:
      - .env
    depends_on:
      postgres-service:
        condition: service_healthy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-public"

      - "traefik.http.services.crypto-app.loadbalancer.server.port=${APP_CRYPTO_PORT}"

      - "traefik.http.routers.crypto-app.rule=Host(`${APP_CRYPTO_DOMAIN}`)"
      - "traefik.http.routers.crypto-app.tls=true"
      - "traefik.http.routers.crypto-app.entrypoints=https"
      - "traefik.http.routers.crypto-app.tls.certresolver=le"

      - "traefik.http.routers.crypto-app-http.middlewares=https-redirect"
    networks:
      - default
      - traefik-public

networks:
  default:
    driver: bridge
  traefik-public:
    external: true
