global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "app"
    static_configs:
      - targets: ["app:3000"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["localhost:8080"]

  - job_name: "node_exporter"
    static_configs:
      - targets: ["localhost:9100"]
